import { StyleSheet } from 'react-native';
import { colors, radius, shadow, spacing } from '@shared/ui';

export const stampPaperPalette = {
  border: '#E8DFCC',
  background: '#FBF7EF',
  ink: '#9C8E72',
  dashedBorder: '#D9CDB4',
  mutedInk: '#C2B69A',
} as const;

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.canvas,
  },
  content: {
    paddingBottom: spacing.xxl,
  },
  captureHeader: {
    minHeight: 58,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  captureTitleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  captureBadge: {
    maxWidth: 104,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radius.full,
    backgroundColor: colors.surfaceSink,
  },
  captureBadgeReady: {
    maxWidth: 112,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radius.full,
    backgroundColor: colors.stampSoft,
  },
  header: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.lg,
    gap: spacing.md,
    backgroundColor: colors.surface,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  progressPanel: {
    padding: spacing.md,
    gap: spacing.sm,
    borderRadius: 14,
    backgroundColor: colors.canvas,
  },
  progressHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  chipRow: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  chip: {
    minHeight: 32,
    paddingHorizontal: spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  chipActive: {
    borderColor: colors.ink,
    backgroundColor: colors.ink,
  },
  grid: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  gridItem: {
    width: '31.7%',
    minHeight: 112,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.md,
    gap: spacing.xs,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  stampIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stampIconDone: {
    borderWidth: 2,
    borderColor: colors.stamp,
    backgroundColor: colors.stampSoft,
  },
  stampIconLocked: {
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: colors.borderMuted,
    backgroundColor: colors.canvas,
  },
  stampIconText: {
    color: colors.stampInk,
  },
  centerText: {
    textAlign: 'center',
  },
  paper: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.lg,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xxl,
    paddingBottom: spacing.lg,
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: stampPaperPalette.border,
    backgroundColor: stampPaperPalette.background,
    overflow: 'hidden',
  },
  paperStripe: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 10,
    backgroundColor: colors.brand,
  },
  paperKicker: {
    color: stampPaperPalette.ink,
  },
  paperTitle: {
    textAlign: 'center',
  },
  paperMeta: {
    color: stampPaperPalette.ink,
    textAlign: 'center',
  },
  stampTarget: {
    width: 192,
    height: 192,
    marginTop: spacing.lg,
    borderRadius: 96,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: stampPaperPalette.dashedBorder,
    backgroundColor: colors.surface,
    ...shadow.e1,
  },
  holdRing: {
    position: 'absolute',
    top: 0,
    left: 0,
  },
  stampTargetPressed: {
    transform: [{ scale: 0.985 }],
    borderColor: colors.brand,
  },
  stampTargetDisabled: {
    opacity: 0.7,
  },
  stampDropLayer: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  },
  holdText: {
    color: stampPaperPalette.ink,
  },
  holdTextActive: {
    color: colors.brand,
  },
  holdSub: {
    maxWidth: 136,
    color: stampPaperPalette.mutedInk,
    textAlign: 'center',
  },
  paperHint: {
    minHeight: 36,
    color: stampPaperPalette.ink,
    textAlign: 'center',
  },
  verifyPanel: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.md,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  verifyPanelReady: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.md,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderRadius: 14,
    backgroundColor: colors.stampSoft,
  },
  verifyIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.stamp,
  },
  verifyCopy: {
    flex: 1,
    minWidth: 0,
  },
  longPressButton: {
    minWidth: 96,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  longPressButtonDisabled: {
    backgroundColor: colors.surfaceSink,
  },
  pressed: {
    opacity: 0.86,
  },
  modalBackdrop: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
    backgroundColor: 'rgba(17, 32, 51, 0.55)',
  },
  successCard: {
    width: '100%',
    maxWidth: 296,
    alignItems: 'center',
    paddingTop: 26,
    paddingHorizontal: spacing.xl,
    paddingBottom: spacing.xl,
    borderRadius: 24,
    backgroundColor: colors.surface,
    ...shadow.e3,
  },
  successStampWrap: {
    position: 'relative',
  },
  successStamp: {
    width: 108,
    height: 108,
    borderRadius: 54,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: colors.stamp,
    backgroundColor: colors.stampSoft,
    transform: [{ rotate: '-7deg' }],
  },
  successStampGlyph: {
    color: colors.stampInk,
  },
  successCheck: {
    position: 'absolute',
    right: -6,
    bottom: -2,
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: colors.surface,
    backgroundColor: colors.stamp,
  },
  successTitle: {
    marginTop: spacing.lg,
    textAlign: 'center',
  },
  successMeta: {
    marginTop: spacing.xs,
    textAlign: 'center',
  },
  successProgress: {
    alignSelf: 'stretch',
    marginTop: spacing.lg,
    padding: spacing.md,
    gap: spacing.sm,
    borderRadius: 14,
    backgroundColor: colors.canvas,
  },
  successProgressHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  successActions: {
    alignSelf: 'stretch',
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.lg,
  },
  successSecondaryButton: {
    flex: 1,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  successPrimaryButton: {
    flex: 1.4,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 13,
    backgroundColor: colors.brand,
  },
  successClose: {
    marginTop: spacing.md,
    textAlign: 'center',
  },
});
