import { StyleSheet } from 'react-native';
import { colors, radius, shadow, spacing } from '@shared/ui';
import { fallbackMapPalette } from './MapView.styles';

export const fallbackMapStageStyles = StyleSheet.create({
  emptyMap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
    gap: spacing.sm,
    overflow: 'hidden',
  },
  fallbackBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: fallbackMapPalette.backdrop,
  },
  fallbackGrid: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.45,
    backgroundColor: 'transparent',
  },
  fallbackBadge: {
    position: 'absolute',
    top: spacing.md,
    left: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.full,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    zIndex: 2,
    ...shadow.e1,
  },
  fallbackStatus: {
    position: 'absolute',
    top: spacing.md,
    right: spacing.md,
    alignItems: 'flex-end',
    gap: 2,
    maxWidth: '52%',
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.md,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderWidth: 1,
    borderColor: colors.border,
    zIndex: 2,
  },
  fallbackRadiusRingOuter: {
    position: 'absolute',
    width: 198,
    height: 198,
    borderRadius: 99,
    top: '50%',
    left: '50%',
    marginLeft: -99,
    marginTop: -99,
    borderWidth: 1,
    borderColor: 'rgba(93, 117, 138, 0.26)',
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  fallbackRadiusRingInner: {
    position: 'absolute',
    width: 124,
    height: 124,
    borderRadius: 62,
    top: '50%',
    left: '50%',
    marginLeft: -62,
    marginTop: -62,
    borderWidth: 1,
    borderColor: 'rgba(94, 101, 164, 0.3)',
    backgroundColor: 'rgba(255,255,255,0.5)',
  },
  fallbackRadiusCore: {
    position: 'absolute',
    width: 18,
    height: 18,
    borderRadius: 9,
    top: '50%',
    left: '50%',
    marginLeft: -9,
    marginTop: -9,
    backgroundColor: colors.brand,
    borderWidth: 4,
    borderColor: 'rgba(255,255,255,0.9)',
  },
  fallbackRadiusLabel: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginLeft: -28,
    marginTop: 108,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: radius.full,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  fallbackTarget: {
    position: 'absolute',
    left: spacing.lg,
    bottom: 96,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadow.e1,
  },
  fallbackTargetCopy: {
    minWidth: 0,
    gap: 1,
  },
  fallbackSpotStrip: {
    position: 'absolute',
    right: spacing.md,
    bottom: 96,
    gap: spacing.xs,
    alignItems: 'flex-end',
    maxWidth: '56%',
  },
  fallbackSpotChip: {
    minHeight: 28,
    maxWidth: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingVertical: 4,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.full,
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderWidth: 1,
    borderColor: colors.border,
  },
  fallbackSpotDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: colors.brand,
  },
  fallbackSpotDotCollected: {
    backgroundColor: colors.locationDot,
  },
  fallbackSpotText: {
    maxWidth: 120,
  },
});
