import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '@shared/ui';
import { fallbackMapPalette, fallbackThumbnailPalette } from './MapView.styles';

export const mapSheetStyles = StyleSheet.create({
  sheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 306,
    paddingTop: spacing.sm,
    paddingHorizontal: spacing.lg,
    paddingBottom: 78,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderTopWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    gap: spacing.md,
    zIndex: 6,
  },
  sheetExpanded: {
    height: '100%',
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    paddingTop: spacing.lg,
  },
  sheetGrabberTouch: {
    minHeight: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetGrabber: {
    width: 38,
    height: 4,
    borderRadius: 2,
    alignSelf: 'center',
    backgroundColor: colors.borderStrong,
  },
  sheetMain: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
  },
  placeThumb: {
    width: 78,
    height: 78,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: colors.skySoft,
  },
  eventThumb: {
    width: 78,
    height: 78,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: colors.locationDot,
  },
  eventThumbFallback: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  eventThumbLabel: {
    position: 'absolute',
    left: 6,
    right: 6,
    bottom: 6,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(19, 34, 51, 0.72)',
  },
  thumbImage: {
    width: '100%',
    height: '100%',
  },
  thumbSky: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.skySoft,
  },
  thumbHill: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 32,
    backgroundColor: fallbackThumbnailPalette.hill,
  },
  thumbRoof: {
    position: 'absolute',
    left: 20,
    top: 30,
    width: 38,
    height: 38,
    backgroundColor: fallbackThumbnailPalette.roof,
    transform: [{ rotate: '45deg' }],
  },
  thumbWall: {
    position: 'absolute',
    left: 22,
    bottom: 16,
    width: 34,
    height: 16,
    backgroundColor: fallbackThumbnailPalette.wall,
  },
  categoryPill: {
    position: 'absolute',
    top: 5,
    left: 5,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: colors.brand,
  },
  sheetCopy: {
    flex: 1,
    minWidth: 0,
    gap: spacing.xs,
  },
  sheetTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  badgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  sheetNotice: {
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    backgroundColor: colors.canvas,
  },
  detailText: {
    color: colors.locationDot,
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  routeButton: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  fallbackList: {
    flexShrink: 1,
    gap: spacing.xs,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  fallbackListExpanded: {
    flex: 1,
    minHeight: 0,
  },
  fallbackListScroller: {
    flex: 1,
    minHeight: 0,
  },
  fallbackListContent: {
    gap: spacing.xs,
    paddingBottom: spacing.sm,
  },
  fallbackListHeader: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  fallbackListHeaderCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  fallbackListCount: {
    minHeight: 28,
    paddingHorizontal: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.full,
    backgroundColor: colors.surfaceSink,
  },
  fallbackRow: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  fallbackRowSelected: {
    borderColor: colors.brand,
    backgroundColor: colors.brandSoft,
  },
  fallbackRowMark: {
    width: 40,
    height: 40,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: colors.surfaceSink,
  },
  fallbackRowMarkImage: {
    width: '100%',
    height: '100%',
  },
  fallbackRowMarkFallback: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: fallbackMapPalette.rowMark,
  },
  fallbackRowMarkDone: {
    backgroundColor: colors.stampSoft,
  },
  fallbackRowCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  fallbackRowTitleLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  fallbackDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: colors.brand,
  },
  fallbackTitle: {
    flex: 1,
    minWidth: 0,
  },
});
