import { StyleSheet } from 'react-native';
import { colors, radius, shadow, spacing } from '@shared/ui';

export const fallbackMapPalette = {
  backdrop: '#F5F1E8',
  rowMark: '#EFE7D6',
} as const;

export const fallbackThumbnailPalette = {
  hill: '#7FA86E',
  roof: '#3E5C46',
  wall: '#B4543A',
} as const;

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    position: 'relative',
    backgroundColor: colors.surface,
  },
  header: {
    minHeight: 48,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
    zIndex: 5,
  },
  logoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  logoMark: {
    width: 26,
    height: 26,
    borderRadius: radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.brand,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  mapArea: {
    flex: 1,
    minHeight: 360,
    position: 'relative',
    backgroundColor: colors.canvas,
  },
  filterPanel: {
    position: 'absolute',
    top: spacing.md,
    left: spacing.md,
    right: 76,
    flexDirection: 'row',
    gap: 4,
    minHeight: 60,
    padding: 5,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: 'rgba(255,255,255,0.95)',
    zIndex: 3,
    ...shadow.e1,
  },
  filterOption: {
    flex: 1,
    minWidth: 0,
    minHeight: 50,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    paddingHorizontal: 2,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  filterOptionActive: {
    borderColor: colors.ink,
    backgroundColor: colors.ink,
  },
  mapControls: {
    position: 'absolute',
    top: spacing.md,
    right: spacing.md,
    gap: spacing.sm,
    zIndex: 3,
  },
  iconButton: {
    width: 38,
    height: 38,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    ...shadow.e1,
  },
  locationPill: {
    position: 'absolute',
    left: spacing.md,
    bottom: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.full,
    backgroundColor: colors.surface,
    zIndex: 3,
    ...shadow.e1,
  },
  locationDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: colors.locationDot,
  },
  mapError: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    bottom: spacing.xxxl,
    padding: spacing.sm,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    zIndex: 4,
  },
  pressed: {
    opacity: 0.86,
  },
});
